# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/naverBlogCrawler.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 589)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 17, 24, 12))
        self.label.setObjectName("label")
        self.btnMove = QtWidgets.QPushButton(Dialog)
        self.btnMove.setGeometry(QtCore.QRect(448, 10, 51, 23))
        self.btnMove.setObjectName("btnMove")
        self.listViewCategory = QtWidgets.QListView(Dialog)
        self.listViewCategory.setGeometry(QtCore.QRect(10, 69, 491, 131))
        self.listViewCategory.setObjectName("listViewCategory")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 48, 12))
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 430, 491, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.chkImgContainYn = QtWidgets.QCheckBox(self.frame)
        self.chkImgContainYn.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.chkImgContainYn.setObjectName("chkImgContainYn")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(140, 60, 71, 16))
        self.label_3.setObjectName("label_3")
        self.txtWaitTime = QtWidgets.QPlainTextEdit(self.frame)
        self.txtWaitTime.setGeometry(QtCore.QRect(215, 57, 91, 21))
        self.txtWaitTime.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtWaitTime.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtWaitTime.setObjectName("txtWaitTime")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(11, 27, 51, 16))
        self.label_6.setObjectName("label_6")
        self.txtSaveDirectory = QtWidgets.QPlainTextEdit(self.frame)
        self.txtSaveDirectory.setGeometry(QtCore.QRect(70, 20, 361, 21))
        self.txtSaveDirectory.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSaveDirectory.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSaveDirectory.setObjectName("txtSaveDirectory")
        self.btnChangeDirectory = QtWidgets.QPushButton(self.frame)
        self.btnChangeDirectory.setGeometry(QtCore.QRect(437, 20, 51, 23))
        self.btnChangeDirectory.setObjectName("btnChangeDirectory")
        self.txtURL = QtWidgets.QPlainTextEdit(Dialog)
        self.txtURL.setGeometry(QtCore.QRect(40, 11, 391, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtURL.sizePolicy().hasHeightForWidth())
        self.txtURL.setSizePolicy(sizePolicy)
        self.txtURL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtURL.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtURL.setObjectName("txtURL")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 36, 12))
        self.label_4.setObjectName("label_4")
        self.listViewArticle = QtWidgets.QListView(Dialog)
        self.listViewArticle.setGeometry(QtCore.QRect(10, 230, 491, 171))
        self.listViewArticle.setObjectName("listViewArticle")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 410, 24, 12))
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(7, 560, 501, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.extractArtcles = QtWidgets.QPushButton(Dialog)
        self.extractArtcles.setGeometry(QtCore.QRect(410, 204, 91, 23))
        self.extractArtcles.setObjectName("extractArtcles")
        self.extractCategory = QtWidgets.QPushButton(Dialog)
        self.extractCategory.setGeometry(QtCore.QRect(400, 40, 101, 23))
        self.extractCategory.setObjectName("extractCategory")
        self.saveBtn = QtWidgets.QPushButton(Dialog)
        self.saveBtn.setGeometry(QtCore.QRect(410, 530, 91, 23))
        self.saveBtn.setObjectName("saveBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Naver Blog Crawler"))
        Dialog.setToolTip(_translate("Dialog", "네이버 블로그 스크랩 도구"))
        Dialog.setWhatsThis(_translate("Dialog", "네이버 블로그 스크랩 도구"))
        self.label.setText(_translate("Dialog", "주소"))
        self.btnMove.setText(_translate("Dialog", "이동"))
        self.label_2.setText(_translate("Dialog", "카테고리"))
        self.chkImgContainYn.setText(_translate("Dialog", "이미지 포함"))
        self.label_3.setText(_translate("Dialog", "대기시간(초)"))
        self.label_6.setText(_translate("Dialog", "저장위치"))
        self.btnChangeDirectory.setText(_translate("Dialog", "변경"))
        self.label_4.setText(_translate("Dialog", "글목록"))
        self.label_5.setText(_translate("Dialog", "옵션"))
        self.extractArtcles.setText(_translate("Dialog", "▼ 글목록 추출"))
        self.extractCategory.setText(_translate("Dialog", "▼ 카테고리 추출"))
        self.saveBtn.setText(_translate("Dialog", "저장"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
